global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'https://webhook.site/9e616c9e-73c6-46d2-87b3-22471816aa47'
