version: '3.8'

services:
  lab_prometheus:
    image: prom/prometheus:latest
    container_name: lab_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prom_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    network_mode: "host"

  lab_grafana:
    image: grafana/grafana:latest
    container_name: lab_grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    network_mode: "host"
    depends_on:
      - lab_prometheus

  lab_alertmanager:
    image: prom/alertmanager:latest
    container_name: lab_alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    network_mode: "host"

  lab_node_exporter:
    image: prom/node-exporter:latest
    container_name: lab_node_exporter
    restart: unless-stopped
    command:
      - "--web.listen-address=localhost:9100"
    network_mode: "host"

volumes:
  prom_data:
  grafana_data:
  alertmanager_data:
